apiVersion: v1
kind: Service             
metadata:
  name: dnsmasq-service
spec:
  type: ClusterIP
{{- if .Values.externalIP.enabled }}
  externalIPs:
  - {{ .Values.externalIP.ip }}
{{- end }}
  ports:
  - port: 53
    name: dns
    protocol: UDP
    targetPort: 53
  selector:
    app: dnsmasq
